### ISSUE TITLE
submit to alternative stores

### ISSUE THREAD

**Issue by natrius** [makubi/SchoolPlanner4Untis#5]
As this seems to be open source, i would recommend to release it also on alternative stores - not every android user has a google 	account.

For example:
Pdassi store - download without registration
Fdroid store - espacially for FOSS

**Comment by natrius** [comment]
Ah, seems like it happened what happens to all school-projects - abandonend when not needed for a good grade.

**Comment by dr03lf** [comment]
Hey @natrius ,

This project has been maintained for about three years. We were working on this app way after we finished school. On my behalf, I've never got a grade for this project, cause I joined the team after I finished school ..... Go and figure.
We stopped development  in September 13, cause 'Gruber und Petter' released their offical version of the Android App. 

Coming back to your initial request: Feel free to fork the project, create your own build and publish it to the stores you named before. The source code is published under the terms of the GPLv3 license, just make sure to be compliant to it. 

Regards
Sebastian
